# Generated by Django 6.0.2 on 2026-02-07 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название папки (максимум 255 символов)', max_length=255, verbose_name='Имя папки')),
                ('materialized_path', models.CharField(blank=True, db_index=True, help_text='Путь к родительской папке для быстрого поиска', max_length=1000, verbose_name='Материализованный путь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(help_text='Пользователь, которому принадлежит папка', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская папка. Если None - корневая папка', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.folder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл в хранилище', upload_to='', verbose_name='Файл')),
                ('original_name', models.CharField(help_text='Имя файла при загрузке', max_length=255, verbose_name='Оригинальное имя')),
                ('size', models.PositiveBigIntegerField(help_text='Размер файла в байтах', verbose_name='Размер')),
                ('mime_type', models.CharField(blank=True, help_text='Тип содержимого файла', max_length=100, verbose_name='MIME-тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_public', models.BooleanField(default=False, help_text='Доступен ли файл по публичной ссылке', verbose_name='Публичный доступ')),
                ('public_link', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор для публичного доступа', unique=True, verbose_name='Публичная ссылка')),
                ('folder', models.ForeignKey(blank=True, help_text='Папка, в которой находится файл', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.folder', verbose_name='Папка')),
                ('owner', models.ForeignKey(help_text='Пользователь, которому принадлежит файл', on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent'], name='storage_fol_owner_i_97468a_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'materialized_path'], name='storage_fol_owner_i_28325a_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent', 'name'], name='storage_fol_owner_i_833ae3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['owner', 'folder'], name='storage_sto_owner_i_e72a81_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['owner', 'uploaded_at'], name='storage_sto_owner_i_5fd734_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['public_link'], name='storage_sto_public__ab21ba_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['is_public'], name='storage_sto_is_publ_c23f11_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['folder', 'original_name'], name='storage_sto_folder__c83208_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storedfile',
            unique_together={('owner', 'folder', 'original_name')},
        ),
    ]
