# Generated by Django 6.0.2 on 2026-02-09 18:27

import django.db.models.deletion
import storage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedfile',
            options={'ordering': ['display_name'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.RemoveIndex(
            model_name='folder',
            name='storage_fol_owner_i_28325a_idx',
        ),
        migrations.RemoveIndex(
            model_name='storedfile',
            name='storage_sto_owner_i_5fd734_idx',
        ),
        migrations.RemoveIndex(
            model_name='storedfile',
            name='storage_sto_public__ab21ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='storedfile',
            name='storage_sto_is_publ_c23f11_idx',
        ),
        migrations.RemoveIndex(
            model_name='storedfile',
            name='storage_sto_folder__c83208_idx',
        ),
        migrations.RenameField(
            model_name='storedfile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='storedfile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='display_name',
            field=models.CharField(default='', max_length=500, verbose_name='Имя для отображения'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(help_text='Название папки', max_length=255, verbose_name='Имя папки'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.folder', verbose_name='Родительская папка'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=storage.models.generate_file_path, verbose_name='Файл в хранилище'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage.folder', verbose_name='Папка'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='MIME-тип'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='original_name',
            field=models.CharField(max_length=500, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='Размер (байты)'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['owner', 'created_at'], name='storage_sto_owner_i_c22923_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['folder', 'display_name'], name='storage_sto_folder__ebcc76_idx'),
        ),
        migrations.AddConstraint(
            model_name='storedfile',
            constraint=models.UniqueConstraint(fields=('owner', 'folder', 'display_name'), name='unique_file_name_per_folder'),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='materialized_path',
        ),
        migrations.RemoveField(
            model_name='storedfile',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='storedfile',
            name='public_link',
        ),
    ]
