# Generated by Django 6.0.2 on 2026-02-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_storedfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='extension',
            field=models.CharField(default='', max_length=10),
        ),
    ]
